version: "3.5"

services:
  syslog:
    image: balabit/syslog-ng:latest
    ports:
      - "514:514"
      - "601:601"
      - "6514:6514"
    volumes:
      - "${PWD}/docker/syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro"
      - "${PWD}/docker/syslog-ng/certs:/etc/syslog-ng/certs:ro"
    command: "--no-caps"

  rsyslog:
    image: rsyslog:latest
    build:
      context: "${PWD}"
      dockerfile: "${PWD}/docker/rsyslog/Dockerfile"
    volumes: 
      - "${PWD}/docker/rsyslog/certs:/etc/rsyslog/certs:ro"