version: "3.5"

services:
  syslog-ng:
    image: balabit/syslog-ng:latest
    container_name: syslog-ng
    ports:
      - "514:514"
      - "601:601"
      - "6514:6514"
    volumes:
      - "${PWD}/docker/syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro"
      - "${PWD}/docker/syslog-ng/certs:/etc/syslog-ng/certs:ro"
    networks:
      - syslog-ng-net
    command: "--no-caps"

  nsyslog:
    image: nsyslog:latest
    container_name: nsyslog
    build:
      context: "${PWD}"
      dockerfile: "${PWD}/docker/nsyslog/Dockerfile"
    volumes: 
      - "${PWD}/docker/nsyslog/certs:/etc/nsyslog/certs:ro"
    networks:
      - syslog-ng-net

networks:
  syslog-ng-net:
    name: syslog-ng-net